return {
  ensure_installed = {
    'bash',
    'c',
    'cmake',
    'cpp',
    'css',
    'dockerfile',
    'gdscript',
    'gitignore',
    'go',
    'gomod',
    'gosum',
    'gotmpl',
    'html',
    'http',
    'javascript',
    'json',
    'lua',
    'markdown',
    'markdown_inline',
    'norg',
    'norg_meta',
    'proto',
    'python',
    'query',
    'rust',
    'sql',
    'toml',
    'typescript',
    'vim',
    'vue',
    'yaml',
    'zsh',
  },

	-- stylua: ignore
  select_keys = {
    { { 'x', 'o' }, 'af', '@function.outer',    { desc = 'Function outer region' } },
    { { 'x', 'o' }, 'if', '@function.inner',    { desc = 'Function inner region' } },
    { { 'x', 'o' }, 'ac', '@class.outer',       { desc = 'Class outer region' } },
    { { 'x', 'o' }, 'ic', '@class.inner',       { desc = 'Class inner region' } },
    { { 'x', 'o' }, 'aa', '@parameter.outer',   { desc = 'Parameter outer region' } },
    { { 'x', 'o' }, 'ia', '@parameter.inner',   { desc = 'Parameter inner region' } },
    { { 'x', 'o' }, 'ab', '@block.outer',       { desc = 'Block outer region' } },
    { { 'x', 'o' }, 'ib', '@block.inner',       { desc = 'Block inner region' } },
    { { 'x', 'o' }, 'ai', '@conditional.outer', { desc = 'Conditional outer region' } },
    { { 'x', 'o' }, 'ii', '@conditional.inner', { desc = 'Conditional inner region' } },
    { { 'x', 'o' }, 'al', '@loop.outer',        { desc = 'Loop outer region' } },
    { { 'x', 'o' }, 'il', '@loop.inner',        { desc = 'Loop inner region' } },
    { { 'x', 'o' }, 'a=', '@assignment.outer',  { desc = 'Assignment outer region' } },
    { { 'x', 'o' }, 'i=', '@assignment.inner',  { desc = 'Assignment inner region' } },
  },
}
